allowBuilds:
  '@scarf/scarf': true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - globals@17.11.0
  - '@nestjs/common@11.2.1'
  - '@nestjs/core@11.2.1'
  - '@nestjs/microservices@11.2.1'
  - '@nestjs/platform-express@11.2.1'
  - '@nestjs/testing@11.2.1'

overrides:
  brace-expansion: ">=5.0.8"
  "js-yaml": ">=5.2.2"
  "fast-uri": ">=3.1.5"
